##########################################################
#  Turn Off Christmas Lights At 2300 Hours
##########################################################
alias: 'Turn off christmas lights at 2300 hours'
trigger:
  - platform: time
    at: '23:00:00'
action:
  - service: homeassistant.turn_off
    entity_id:
      - switch.extchristmaslights

