##########################################################
#  Turn On Front Path Lights When Going To Work
##########################################################
alias: 'Turn on front path lights before work'
trigger:
  - platform: time
    at: '07:00:00'
condition:
- condition: state
  entity_id: input_boolean.mode_away
  state: 'off'
- condition: time
  weekday:
    - mon
    - tue 
    - wed
    - thu
    - fri
action:
  - service: homeassistant.turn_on
    entity_id:
      - light.plfront

