##########################################################
#  Turn Off Front Path Lights Before Bed Weekday
##########################################################
alias: 'Turn off front path lights at 2230 hours'
trigger:
  - platform: time
    at: '22:30:00'
condition:
- condition: time
  weekday:
    - sun
    - mon
    - tue
    - wed
    - thu
action:
  - service: homeassistant.turn_off
    entity_id:
      - light.plfront

