##########################################################
#  Turn On Front Path Lights When Going To Work
##########################################################
- alias: 'Turn on front path lights before work'
  trigger:
    - platform: time
      at: '06:30:00'
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: input_boolean.mode_away
        state: 'off'
      - condition: time
        weekday:
          - mon
          - tue
          - wed
          - thu
          - fri
      - condition: state
        entity_id: sun.sun
        state: 'below_horizon'
  action:
    - service: homeassistant.turn_on
      entity_id:
        - light.plfront
        - input_boolean.auto_plfront

##########################################################
#  Turn On Front Path Lights at Sunset
##########################################################
- alias: 'Turn on front path lights at sunset'
  trigger:
    - platform: sun
      event: sunset
  action:
    - service: homeassistant.turn_on
      entity_id:
        - light.plfront

##########################################################
#  Turn Off Front Path Lights At Sunrise
##########################################################
- alias: 'Turn off front path lights at sunrise'
  trigger:
    - platform: sun
      event: sunrise
  action:
    - service: homeassistant.turn_off
      entity_id:
        - light.plfront

##########################################################
#  Turn Off Front Path Lights Before Bed Weekday
##########################################################
- alias: 'Turn off front path lights at 2230 hours'
  trigger:
    - platform: time
      at: '22:30:00'
  condition:
  - condition: time
    weekday:
      - sun
      - mon
      - tue
      - wed
      - thu
  action:
    - service: homeassistant.turn_off
      entity_id:
        - light.plfront

##########################################################
#  Turn Off Front Path Lights Before Bed Weekend
##########################################################
- alias: 'Turn off front path lights at 2330 hours'
  trigger:
    - platform: time
      at: '23:30:00'
  condition:
  - condition: time
    weekday:
      - fri
      - sat
  action:
    - service: homeassistant.turn_off
      entity_id:
        - light.plfront

