##########################################################
#  Turn Off Master Bedroom Surge Strip After Getting Up
##########################################################
alias: 'Turn off master bedroom surge strip after getting up'
trigger:
  - platform: time
    at: '10:00:00'
action:
  - service: switch.turn_off
    entity_id:
      - switch.mbrsurgestrip

