##########################################################
#  Turn On Fish Tank Light
##########################################################
- alias: 'Turn on tank lights after sunrise'
  trigger:
    - platform: sun
      event: sunrise
      offset: "01:00:00"
  action:
    - service: homeassistant.turn_on
      entity_id:
        - switch.master_bed_outlet_19

##########################################################
#  Turn Off Fish Tank Light before bed
##########################################################
- alias: 'Turn off tank lights before bed'
  trigger:
    - platform: time
      at: '21:30:00'
  action:
    - service: homeassistant.turn_off
      entity_id:
        - switch.master_bed_outlet_19
