##########################################################
#  Garage Door - Left open after dark
##########################################################
- alias: 'Notification - Garage door left open after dark'
  trigger:
    - platform: state
      entity_id:
        - binary_sensor.garagedoor_state
      to: 'on'
      for:
        minutes: 30
  condition:
    condition: or
    conditions:
      - condition: sun
        after: sunset
        after_offset: "-00:30:00"
      - condition: sun
        before: sunrise
        before_offset: "00:30:00"
  action:
    - service: notify.pb_notify
      data:
        title: "URGENT: Garage Door Left Open"
        message: "The garage door has been left open for more than 30 minutes after dark.."

##########################################################
#  Garage Door - State opened while away
##########################################################
#- alias: 'Notification - Garage door opened while away'
#  trigger:
#    - platform: state
#      entity_id:
#        - binary_sensor.garagedoor_state
#      to: 'on'
#  condition:
#    - condition: state
#      entity_id: input_boolean.mode_away
#      state: 'on'
#  action:
#    - service: notify.pb_notify
#      data:
#        title: "URGENT: Garage Door OPENED While Away"
#        message: "The garage door has been OPENED. The house is no longer secure."

##########################################################
#  Garage Door - State closed while away
##########################################################
#- alias: 'Notification - Garage door closed while away'
#  trigger:
#    - platform: state
#      entity_id:
#        - binary_sensor.garagedoor_state
#      to: 'off'
#  condition:
#    - condition: state
#      entity_id: input_boolean.mode_away
#      state: 'on'
#  action:
#    - service: notify.pb_notify
#      data:
#        title: "URGENT: Garage Door CLOSED While Away"
#        message: "The garage door has been CLOSED and should now be secure."
