##########################################################
#  Garage Door - Left open after dark
##########################################################
alias: 'Notification - Garage door left open after dark'
trigger:
  - platform: state
    entity_id:
      - binary_sensor.garagedoor_state
    to: 'on'
    for:
      minutes: 30
condition:
  condition: or
  conditions:
    - condition: sun
      after: sunset
      after_offset: "-00:30:00"
    - condition: sun
      before: sunrise
      before_offset: "00:30:00"
action:
  - service: notify.pb_notify
    data:
      title: "URGENT: Garage Door Left Open"
      message: "The garage door has been left open for more than 30 minutes after dark.."

