##########################################################
#  Adjust Family Room Lighting
##########################################################
- alias: 'Adjust Family Room Lights'
  hide_entity: True
  trigger:
    - platform: state
      entity_id:
        - input_number.fr_main_light_slider
  condition:
    - condition: state
      entity_id: light.fr_main_lights_17
      state: 'on'
  action:
    - service: light.turn_on
      data_template:
        entity_id: light.fr_main_lights_17
        brightness_pct: '{{ trigger.to_state.state }}'

##########################################################
#  Report Family Room Light Status
##########################################################
#- alias: 'Family Room Lights Status'
#  trigger:
#    - platform: state
#      entity_id:
#        - light.fr_main_lights_17
#  action:
#    - service: input_number.set_value
#      data_template:
#        entity_id: input_number.fr_main_light_slider
#        value: '{{ states.sensor.fr_main_light_intensity.state }}'
