##########################################################
#  Turn On Grow Lights At Sunrise
##########################################################
- alias: 'Turn on grow lights at sunrise'
  trigger:
    - platform: sun
      event: sunrise
      offset: "01:00:00"
  action:
    - service: homeassistant.turn_on
      entity_id:
        - light.maingrowlights
        - light.secondarygrowlights

##########################################################
#  Turn Off Grow Lights at Sunset
##########################################################
- alias: 'Turn off grow lights at sunset'
  trigger:
    - platform: sun
      event: sunset
      offset: "-01:00:00"
  action:
    - service: homeassistant.turn_off
      entity_id:
        - light.maingrowlights
        - light.secondarygrowlights
