##########################################################
#  Turn Off Grow Lights at Sunset
##########################################################
alias: 'Turn off grow lights at sunset'
trigger:
  - platform: sun
    event: sunset
    offset: "-01:00:00"
action:
  - service: homeassistant.turn_off
    entity_id:
      - light.maingrowlights
      - light.secondarygrowlights
