##########################################################
#  Turn On Living Room Side Lamp When Going To Work
##########################################################
alias: 'Turn on living room table lamp before work'
trigger:
  - platform: time
    at: '06:30:00'
condition:
- condition: time
  weekday:
    - mon
    - tue
    - wed
    - thu
    - fri
action:
  - service: homeassistant.turn_on
    entity_id:
      - light.lrsidelamp

