##########################################################
#  Turn Off Living Room Side Lamp Before Bed
##########################################################
alias: 'Turn off living room side lamp at 2300 hours'
trigger:
  - platform: time
    at: '23:00:00'
action:
  - service: homeassistant.turn_off
    entity_id:
      - light.lrsidelamp

