##########################################################
#  Turn On Living Room Side Lamp at Sunset
##########################################################
alias: 'Turn on living room side lamp at sunset'
trigger:
  - platform: sun
    event: sunset
    offset: "-00:30:00"
action:
  - service: homeassistant.turn_on
    entity_id:
      - light.lrsidelamp

