##########################################################
#  Turn Off Exterior Devices at Midnight
##########################################################
alias: 'Turn off all exterior devices at midnight'
trigger:
  - platform: time
    at: '00:00:00'
action:
  - service: homeassistant.turn_off
    entity_id:
      - group.exterior_accessories
      - group.pathlighting
      - group.pond
