######################################################
#  BINARY SENSORS
######################################################

# Garage Door Position Status
- platform: mqtt
  name: 'garagedoor_state'
  state_topic: 'basement/garagedoor/status'
  payload_on: "ON"
  payload_off: "OFF"
  device_class: opening

######################################################
#  Network Devices
######################################################
- platform: ping
  host: !secret skynet_rt
  name: Skynet_RT

- platform: ping
  host: !secret skynet_sw1
  name: Skynet_SW1

- platform: ping
  host: !secret skynet_sw2
  name: Skynet_SW2

- platform: ping
  host: !secret skynet_ap1
  name: Skynet_AP1

- platform: ping
  host: !secret skynet_ap2
  name: Skynet_AP2

- platform: ping
  host: !secret skynet_cluster
  name: Skynet_Cluster

- platform: ping
  host: !secret skynet_serv
  name: Skynet_Serv

- platform: ping
  host: !secret printer_clp315w
  name: Printer_CLP315w

- platform: ping
  host: !secret fullforce
  name: FullForce

######################################################
#  Scripted Checks
######################################################
- platform: command_line
  name: WAN Status
  command: "/home/homeassistant/.homeassistant/scripts/wan_test.sh"
  device_class: connectivity
  payload_on: "Up"
  payload_off: "Down"
