######################################################
#  Home Assistant Configuration
######################################################
homeassistant:
  latitude: !secret hass_latitude
  longitude: !secret hass_longitude
  elevation: !secret hass_elevation
  unit_system: imperial
  time_zone: !secret hass_timezone
  temperature_unit: F
  name: !secret hass_name
  customize: !include customize.yaml

  auth_providers:
   - type: homeassistant
   # Uncomment to enable legacy API password support
   # - type: legacy_api_password    

# Enable authentication UI
auth:

# Enables configuration UI
config:

# Enables the frontend and includes available themes
frontend:
  themes: !include_dir_merge_named themes

# Configuration for the web UI
http:
  #api_password: !secret hass_password
  server_host: !secret serv_address
  server_port: !secret serv_port
  ip_ban_enabled: true
  login_attempts_threshold: 3
  base_url: !secret serv_baseurl
  use_x_forwarded_for: true
  trusted_proxies:
    - !secret proxy_ip
  cors_allowed_origins:
    - !secret cors_fqdn_1

# Checks for available updates
updater:
  include_used_components: false
  reporting: false

# Discover some devices automatically
#discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Track the sun
sun:

# Logging and display of events
recorder: !include recorder.yaml
history: !include history.yaml
logbook: !include logbook.yaml

# HASS system log level configuration
logger: !include logger.yaml

# Let homeassistant know about the local MQTT broker and client
mqtt:
  broker: !secret mqtt_serverip
  port: !secret mqtt_serverport
  client_id: !secret mqtt_clientid
  username: !secret mqtt_user
  password: !secret mqtt_password

# Let homeassistant know about the Vera smart controller
vera:
  vera_controller_url: !secret vera_url
  # Keep the sensor list clean and exclude system devices
  exclude: [ 199, 299]

# Text to speech
# tts:
#   - platform: google

######################################################
#  CONFIGURATION INCLUDES
######################################################
automation: !include_dir_merge_list automation
binary_sensor: !include binary_sensors.yaml
climate: !include climate.yaml
input_boolean: !include input_boolean.yaml
input_number: !include input_number.yaml
google_assistant: !include gass.yaml
group: !include groups.yaml
light: !include lights.yaml
media_player: !include mediaplayer.yaml
notify: !include notify.yaml
script: !include scripts.yaml
sensor: !include sensors.yaml
switch: !include switches.yaml
