######################################################
#  Home Assistant Configuration
######################################################
homeassistant:
  latitude: !secret hass_latitude
  longitude: !secret hass_longitude
  elevation: !secret hass_elevation
  unit_system: imperial
  time_zone: !secret hass_timezone
  temperature_unit: F
  name: !secret hass_name
  customize: !include customize.yaml

# Enables the frontend
frontend:
  #themes: !include themes/dark_cyan.yaml
  themes: !include themes/dark_red.yaml
  #themes: !include themes/dark_orange.yaml

# Enables configuration UI
config:

http:
  api_password: !secret hass_password
  trusted_networks:
    - 127.0.0.1
    - ::1
    - 10.0.1.0/24
    - 10.0.10.0/24
  ip_ban_enabled: True
  login_attempts_threshold: 5


# Checks for available updates
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
updater:
  include_used_components: false
  reporting: false

# Discover some devices automatically
# discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
# conversation:

# Enables support for tracking state changes over time
history:

# Logbook of events customized and log level configuration
logbook: !include logbook.yaml
logger: !include logger.yaml

# Track the sun
sun:

# Text to speech
# tts:
#   - platform: google

# Let homeassistant know about the local MQTT broker and client
mqtt:
  broker: 'localhost'
  port: 1883
  client_id: !secret mqtt_clientid
  username: !secret mqtt_user
  password: !secret mqtt_password

######################################################
#  CONFIGURATION INCLUDES
######################################################

automation: !include_dir_list automation
binary_sensor: !include binary_sensor.yaml
input_boolean: !include input_boolean.yaml
group: !include groups.yaml
light: !include lights.yaml
notify: !include notify.yaml
script: !include scripts.yaml
sensor: !include sensors.yaml
switch: !include switch.yaml
