######################################################
#  Logbook configuration
######################################################
  exclude:
    entities:
      - sensor.date
      - sensor.time
    domains:
      - group
