#################################################################
## Logger
#################################################################
# Log Severities: notset, debug, info, warn, warning, error, fatal, critical

default: warn
logs:
  homeassistant.core: warning
  homeassistant.components.automation: warn
  homeassistant.components.discovery: warn
  homeassistant.components.http: warn
  homeassistnat.components.mqtt: info
  homeassistant.components.media_player: warn
  homeassistant.components.recorder: error
  homeassistant.components.sensor.darksky: warn
  homeassistant.components.binary_sensor.ping: warn
  homeassistant.helpers.script: warn
  homeassistant.helpers.entity: critical
  homeassistant.exceptions: info
  py.warnings: error
  root: warn
