######################################################
#  Pushbullet notification service
######################################################
- platform: pushbullet
  name: 'pb_notify'
  api_key: !secret pushbullet_apikey
