# Exterior Christmas Lights
- platform: mqtt
  name: 'extchristmaslights'
  state_topic: 'exterior/extchristmaslights/status'
  command_topic: 'exterior/extchristmaslights/switch'

# Garage Door Trigger
- platform: mqtt
  name: 'garagedoor_command'
  command_topic: 'basement/garagedoor/switch'
  payload_on: "ON"
  payload_off: "OFF"

# Master Bedroom Surge Strip
- platform: mqtt
  name: 'mbrsurgestrip'
  state_topic: 'secondfloor/mbrsurgestrip/status'
  command_topic: 'secondfloor/mbrsurgestrip/switch'

# Pond Waterfall Pump
- platform: mqtt
  name: 'waterfallpump'
  state_topic: 'exterior/pondcontrol/status'
  command_topic: 'exterior/pondcontrol/switch'
  optimistic: false
